### ISSUE TITLE
Available Online Actuators

### ISSUE THREAD

**Issue by SteveMacenski** [mit-biomimetics/Cheetah-Software#17]
Hi,

I couple of in-depth searches looking for adequate actuators for a Cheetah Mini-like (or Cheetah Mini-copy?) yields [this](https://www.robotdigg.com/product/1667) and [this](https://www.aliexpress.com/item/32985671853.html?spm=a2g0o.detail.1000060.3.3e102ef5X1lUEN&gps-id=pcDetailBottomMoreThisSeller&scm=1007.13339.146401.0&scm_id=1007.13339.146401.0&scm-url=1007.13339.146401.0&pvid=d1c5eb92-8139-4485-b3b1-950fde3ec261). 

I was curious if you had experiences with these or could comment on them. I have to assume they're just knock-offs from online documentation but I also wasn't sure if you were in the process of mass producing them enough that one of these vendors is actually legitimate. I've seen a variety of interest around online with these actuators and I'm sure it would help all of us looking at this from the outside if any of these are actually good starts (or the actual actuators you're using) vs. things that could make us all waste a bunch of time.

**Comment by dicarlo236** [comment]
We aren't involved at all with any of these companies or these products, even if they are using our pictures/documents.  They all seem to be designed based on pictures in our papers and are different from our designs.

I'm not sure how well they work.  I've only seen one up close, and there was nothing obviously bad about the mechanical design, but the motor controller did not have phase current sensors, which you need to implement torque control well.

There is this video https://www.youtube.com/watch?v=0P4E0bzkbXM from the company "Smart Engines"
which is using the software in this repository and possibly one of these cheaply available actuators. The robot walks kind of strangely in this video (it is too low to the ground compared to the default configuration), but I don't know if this is because of the actuators or not.

**Comment by SteveMacenski** [comment]
Ah got it, I assumed as much - figured I'd reach out for a definite answer (and leave a paper trail for future googlers).

Thanks for the time.

**Comment by qiayuanl** [comment]
The software set up of cheetah on [https://www.youtube.com/watch?v=0P4E0bzkbXM](url) is done by me. 'Smart Engines" send me a mini cheetah and I help them set up and run it successfully use the software on this repository.
I tried other unofficial Cheetah Mini-like actuators which all made in China(included your post), and the actuators made by "Smart Engines" have the best performance.
