### ISSUE TITLE
Cannot run simulator

### ISSUE THREAD

**Issue by mklvcm** [mit-biomimetics/Cheetah-Software#21]
Hi guys, 

I'm trying to run simulator and I'm getting this error. Please see detailed screenshots. Any ideas what's wrong?

Thanks,
Mike.

![1 - simulator started](https://user-images.githubusercontent.com/54096564/72061138-6470a100-3329-11ea-8bf8-e27463391865.png)

![2 - simulator window](https://user-images.githubusercontent.com/54096564/72061153-6b97af00-3329-11ea-9865-65f9372a94ce.png)

![3 - controller](https://user-images.githubusercontent.com/54096564/72061160-705c6300-3329-11ea-97a0-7ffe16b34245.png)

![4 - error](https://user-images.githubusercontent.com/54096564/72061172-75211700-3329-11ea-85ad-057dd525738e.png)

![5 - simulator failure](https://user-images.githubusercontent.com/54096564/72061180-7b16f800-3329-11ea-95a4-9a16948deb13.png)

**Comment by dicarlo236** [comment]
The error message you see is the robot control code saying that it didn't expect to receive a parameter named "Kd_body".  This is because the default control parameters that are loaded into the sim GUI are for the MIT_Controller/mit_ctrl robot control code, and not the JPos_Controller.

I'd recommend running the MIT Controller instead, as the JPos_Controller doesn't do very much.

**Comment by mklvcm** [comment]
Thank you very much for your response!
This got me a big further.
It looks like simulator has started and maybe even tried to make some movements.
However I'm now getting different error.
Why does it try to access ttyUSB0?

![1 - simulator window](https://user-images.githubusercontent.com/54096564/72151493-78d19e00-33fc-11ea-8e17-389c4f1db968.png)

![2 - controller window](https://user-images.githubusercontent.com/54096564/72151501-7ec77f00-33fc-11ea-9aa8-b351d034d7fb.png)

![3 - render](https://user-images.githubusercontent.com/54096564/72151512-838c3300-33fc-11ea-9737-7d44f526cd7b.png)

**Comment by dicarlo236** [comment]
It looks like the simulation is running for a small amount of time (the sim-time has increased), but the robot code is not responding.  The simulator will assume the robot code has crashed if it does not receive any updates for 1 second.

This can happen for a number of reasons:
- There is a strange issue with LCM and Wi-Fi sometimes.  Try disabling Wi-Fi or other network adapters and trying again.  If you disable Wi-Fi and get an LCM related error, follow the directions on the top of this page: https://lcm-proj.github.io/multicast_setup.html
- If you are running on a laptop or slower computer (especially if you have Ubuntu in a VM), make sure the computer is plugged in.  The power save mode on battery sometimes causes issues.
- Make sure there is nothing else running in the background.

**Comment by mklvcm** [comment]
Looks like I'm making some progress.
I had to enable LCM multicast and it works now (WiFi disabling is not needed).
I still don't have gamepad (waiting for delivery) so my first question is can I control robot by keyboard?

Second question, is that upon start the scene looks weird and I suspect something is wrong. 
There are two copies of the robot rendered and poor thing looks like it is stuck between heaven and hell desperately trying to do something.
Is it ... normal?...

![1](https://user-images.githubusercontent.com/54096564/72212664-26939880-3534-11ea-919c-0f5b6c3497ac.png)

![2](https://user-images.githubusercontent.com/54096564/72212668-2abfb600-3534-11ea-8bc3-f6d2c7f833e2.png)

**Comment by dicarlo236** [comment]
Yes, that's actually working.  The initial state of the simulator looks very weird, but it is okay.  Once the controller starts, it will look better.

The blue/purple robot is the actual state of the robot in the simulator.  It's a little bit into the ground because our collision model for the body isn't super accurate in terms of the shape.

The white robot is the robot controller's estimate of the state.  Because nothing is initialized yet, it's in a mode where it thinks that all four feet are on the ground.  But in reality, the feet are a little bit above the ground, so the robot appears under the ground.  Once the robot is standing or trotting, you should see the state estimate robot (white) match the simulator state robot (blue/purple).

The ESTOP means that the control code is in E-Stop mode.  We have two different methods of controlling the robot, either the Logitech USB controller, or with an R/C radio for model airplanes, for when we need to run the real robot wirelessly.  The default is the R/C radio, and if it is not detected, the default is E-Stop.  In the simulator window, in the center column, you can set the variable "use_rc" to 0, and it will use the Logitech USB controller.  I believe the default for the Logitech controller code is to take it out of E-Stop even if you don't have it plugged in, so when you do this you should see the legs move.  If you want to see the robot trot, you can set the control_mode in the center column to "6" to have it stand up, and "4" to start trotting.

Currently we don't have code for using the keyboard to control the robot, but this is on our list of things to add.
